//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JDMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int id { get; set; }
        public string name { get; set; }
        public double InPrice { get; set; }
        public double OutPrice { get; set; }
        public Nullable<int> Cateid { get; set; }
        public string Desn { get; set; }
        public string picture { get; set; }
        public System.DateTime Createdate { get; set; }
        public string Unit { get; set; }
        public int Quantity { get; set; }
        public string Remark { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
