//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JDMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string username { get; set; }
        public string password { get; set; }
        public string age { get; set; }
        public System.DateTime birthday { get; set; }
        public string location { get; set; }
        public string location2 { get; set; }
        public string location3 { get; set; }
        public string permission { get; set; }
        public string shopcart { get; set; }
        public int accountlevel { get; set; }
        public int plus { get; set; }
    }
}
